# Generated by Django 5.1.8 on 2025-05-18 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0705_stream_subscriber_count_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageDeliveryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Sent"), (2, "Delivered"), (3, "Read")], default=1
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_statuses",
                        to="zerver.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_delivery_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["message", "recipient"], name="zerver_mess_message_882965_idx"
                    ),
                    models.Index(
                        fields=["recipient", "status"], name="zerver_mess_recipie_b24a5d_idx"
                    ),
                ],
                "unique_together": {("message", "recipient")},
            },
        ),
    ]
